### ISSUE TITLE
ukažka testu pred spustenim

### ISSUE THREAD

**Issue by kikaika** [edupagehack/edupagetesthack#12]
ahoj, prepáč ak som prehliadla odpoveď na moju otázku, ale nemáš kód na to, aby sa mi test ukázal pred časom oficialneho spustenia? vopred ďakujem :)

**Comment by addsky11001** [comment]
> ahoj, prepáč ak som prehliadla odpoveď na moju otázku, ale nemáš kód na to, aby sa mi test ukázal pred časom oficialneho spustenia? vopred ďakujem :)

Ahoj, sice niesom oficialne do tohoto zapojeny ale mal som napisany kod ktory to dokazal. Bohužial je to momentálne patchnuté. 
![edubug](https://user-images.githubusercontent.com/79278425/108404026-aacc4b00-721f-11eb-86a5-6da0a719f207.png)
Dá sa to jedine že sa rozšifruje srcid toho daného testu, ale je to veľmi zdlhavé a nevyužitelné.
S pozdravom addsky11001

**Comment by markotomcik** [comment]
> ahoj, prepáč ak som prehliadla odpoveď na moju otázku, ale nemáš kód na to, aby sa mi test ukázal pred časom oficialneho spustenia? vopred ďakujem :)

Momentálne sa sústredime na odhaľovanie odpovedí na samotnom teste. Ak bude kód na odhalenie odpovedí pred spustením bude to v [README](https://github.com/edupagehack/edupagetesthack/blob/main/README.md)
