### ISSUE TITLE
nazdar

### ISSUE THREAD

**Issue by lexXx11** [edupagehack/edupagetesthack#15]
Nazdar dnes som skúšal Váś kód fungoval super no niektore odpovede boli spravne a niektore nie. To je potom asi zo strany ucitela ze zadal zle spravne odpovede ci?

**Comment by ivanhrabcak** [comment]
Ak máš najnovšiu verziu a pred otázkou je varovanie, nie je to chyba učiteľa, ale snaha zo strany edupage opravit tento bug. Ak máš najnovšiu verziu a varovania si nevidel tak je to pravdepodobne chyba zo strany ucitela.
