### ISSUE TITLE
Nefungujúce úlohy typu ABCD a vypisovacie otázky/úlohy

### ISSUE THREAD

**Issue by Martinko366** [edupagehack/edupagetesthack#23]
Všetci z triedy ďakujeme za toto rozšírenie, zachraňuje to životy spolužiakov, len narazili sme na problém.
Viem o tom že úlohy ABCD nefungujú, resp. pravdepodobne nie sú pridané ale je tu ešte jeden problém: vypisovacie úlohy.

Vypisovacie úlohy fungovali bezproblémovo až do asi Štvrtku minulého týždňa. Z nejakého dôvodu nefungujú len tak, z ničoho nič.

Predom ďakujem za odpoveď...

**Comment by ivanhrabcak** [comment]
https://github.com/edupagehack/edupagetesthack/pull/24
