### ISSUE TITLE
pozrieť test pred spustením

### ISSUE THREAD

**Issue by popo11615** [edupagehack/edupagetesthack#28]
Dal by sa nejakým spôsobom pozrieť test pred jeho spustením?

**Comment by jozkomrkvic** [comment]
To by zaujimalo aj mna.

**Comment by ivanhrabcak** [comment]
Nie a ani táto funkcia nebude nikdy súčasťou tohto doplnku

**Comment by jozkomrkvic** [comment]
A vy by ste mi to vedeli poprípade za nejaký doplatok vedeli zistiť?

Dňa št 25. 3. 2021 o 18:28 ivanhrabcak ***@***.***>
napísala(a):

**Comment by ivanhrabcak** [comment]
nie.
